/** @module "tiapp.xml" */

var constants = require('./constants'),
	fs = require('fs'),
	ItemGroup = require('./ItemGroup'),
	path = require('path'),
	TiappError = require('./TiappError'),
	U = require('./util'),
	xml = require('./xml');

/**
 * Determines the location of the tiapp.xml file. It will search the current directory,
 * and all other directories higher in the view hierarchy, in order. If it does not find
 * a tiapp.xml in any of these directories, null is returned.
 *
 * @example
 * var file = require('tiapp.xml').find();
 * if (file === null) {
 *   throw new Error('tiapp.xml not found');
 * } else {
 *   // do stuff
 * }
 *
 * @returns {String|null} The location of the tiapp.xml file, or null if not found.
 */
exports.find = function find() {
	var cwd = process.cwd(),
		parts = cwd.split(path.sep);

	// remove empty element
	if (parts[0] === '') {
		parts.shift();
	}

	// iterate up through hierarchy to try and find a tiapp.xml
	for (var i = 0, len = parts.length; i < len; i++) {
		var p = (/^win/.test(process.platform) ? '' : path.sep) +
			path.join.apply(path, parts.slice(0, len-i).concat('tiapp.xml'));
		if (fs.existsSync(p) && fs.statSync(p).isFile()) {
			return p;
		}
	}

	return null;
};

/**
 * Parses the given string as xml and returns a new {@link Tiapp} instance.
 *
 * @example
 * // read tiapp.xml, give it to parse()
 * var fs = require('fs');
 * var xml = fs.readFileSync('/path/to/tiapp.xml', 'utf8');
 * var tiapp = require('tiapp.xml').parse(xml);
 *
 * @example
 * // Parse with a string of xml
 * var tiapp = require('tiapp.xml').parse('<ti:app><!-- ... --></ti:app>');
 *
 * @param {String} [str] XML string to be parsed, presumedly a tiapp.xml
 * @param {String} [file] A file to associate with the parse operation. This will be
 *                        assigned to this.file.
 *
 * @returns {Tiapp} A new instance of {@link Tiapp} based on the parsed xml
 * @throws {TiappError} Must be valid xml in tiapp.xml format
 */
exports.parse = function parse(str, file) {

	// make sure xml is a string
	if (!str || !U.isString(str)) {
		throw new TiappError('Bad argument. xml must be a string.', str);
	}

	// parse the xml
	var doc = xml.parseFromString(str);

	// make sure it's actually a tiapp.xml
	if (!doc || !doc.documentElement) {
		throw new TiappError('No XML document created', str);
	} else if (doc.documentElement.nodeName !== 'ti:app') {
		throw new TiappError('Parsed XML is not a tiapp.xml', str);
	}

	// create an instance of Tiapp
	return new Tiapp(file, doc);
};

/**
 * Parses the given file as a tiapp.xml file and returns a new {@link Tiapp} instance. If a file is not
 * provided, {@link Tiapp#find|find()} will attempt to find one automatically. The file is
 * validated, read, and then {@link Tiapp#parse|parse()} is called.
 *
 * @example
 * // load with a file path
 * var tiapp = require('tiapp.xml').load('/path/to/tiapp.xml');
 *
 * @example
 * // load without a file path, letting find() try to find it for you
 * var tiapp = require('tiapp.xml').load();
 *
 * @param {String} [file] Path to the tiapp.xml file
 *
 * @returns {Tiapp} A new instance of {@link Tiapp} based on the loaded file
 * @throws {TiappError} Must be able to find a tiapp.xml file
 */
exports.load = function load(file) {

	// make sure we have a file
	if (typeof file !== 'undefined' && !U.isString(file)) {
		throw new TiappError('Bad argument. If defined, file must be a string.', file);
	}
	file = file || exports.find();
	if (!file || (file && !fs.existsSync(file))) {
		throw new TiappError('tiapp.xml not found', file);
	}

	// parse the file
	return exports.parse(fs.readFileSync(file, 'utf8'), file);
};

/**
 * Creates an instance of Tiapp
 * @constructor
 *
 * @param {String} [file] Path to the tiapp.xml file to load. If one is not provided,
 *                        {@link Tiapp#find|find()} will attempt to find and load one automatically.
 * @param {Object} [doc] The XML document object used internally for Tiapp operations
 *
 * @readonly
 * @property {String} file Path to the tiapp.xml file that loaded this instance
 * @property {Object} doc XML document object, generated by {@link Tiapp#parse|parse()}. Generally you'll
 *                        use the Tiapp API and won't access this directly. If you need it, though, it is
 *                        available. Its usage can be found at https://github.com/jindw/xmldom.
 *
 * @returns {Tiapp} An instance of {@link Tiapp}
 */
function Tiapp(file, doc) {
	var self = this;

	Object.defineProperty(this, 'file', {
		configurable: true,
		enumerable: true,
		writable: false,
		value: file
	});
	this.doc = doc;

	this.modules = new ItemGroup(this.doc, 'modules');
	this.plugins = new ItemGroup(this.doc, 'plugins');

	this.property = {

	};

	// deployment-target
	// property

	constants.topLevelElements.forEach(function(prop) {
		Object.defineProperty(self, prop, {
			get: function() {
				var nodes = self.doc.documentElement.getElementsByTagName(prop);
				if (nodes && nodes.length) {
					return xml.getNodeText(nodes.item(0));
				} else {
					return null;
				}
			},
			set: function(val) {
				xml.setTextNode(prop, val, self.doc.documentElement, self.doc);
			}
		});
	});
}

/**
 * Writes the current Tiapp object to its tiapp.xml file
 *
 * @param {String} [file=this.file] The file to which to write the Tiapp
 */
Tiapp.prototype.write = function write(file) {
	file = file || this.file;
	fs.writeFileSync(file, xml.nodeToString(this.doc));
};
